version: "3.8"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - default
    volumes:
      - ./backend/docker-setup/mongo/db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./backend/docker-setup/mongo/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mern_docker_starter
      - MONGO_INITDB_USER=local_user
      - MONGO_INITDB_PASSWORD=Password123

  backend:
    container_name: node
    build:
      context: ./backend
      dockerfile: docker-setup/node/development/Dockerfile
    networks:
      - default
      - frontend
    volumes:
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env.development
    depends_on:
      - mongo
    ports:
      - "8080:4000"

  frontend:
    container_name: react-mern-docker-boilerplate
    build:
      context: ./frontend
      dockerfile: docker-setup/react/development/Dockerfile
    networks:
      - frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongodb_data_container:

networks:
  frontend:
